env:
  DOCKER_COMPOSE_VERSION: 1.25.4
services:
  - docker

jobs:
  include:
    - stage: container creation and publishing
      install: skip
      script: travis/containerCreation.sh um-login-persistence

    - stage: smoke and acceptance test
      install: skip # without this there's a `git clone` executed!
      script: travis/acceptanceTest.sh um-login-persistence 8080 7000 # Service name + external port + internal port for docker

    - stage: release
      if: branch = master AND NOT type IN (pull_request)
      install: skip
      script: travis/release.sh um-login-persistence

notifications:
  slack: eoepca:Msk9hjQKAbwSYcVWiepenPim
  on_success: change
  on_failure: change
