env:
  DOCKER_COMPOSE_VERSION: 1.25.4
services:
  - docker

jobs:
  include:
    - stage: container creation and publishing
      install: skip
      script: travis/containerCreation.sh um-login-persistence

    - stage: smoke and acceptance test
      install: pip install -r requirements.txt
      script: python3 travis/acceptanceTest.sh # Validation of the LDIF data to be inserted

    - stage: release
      if: branch = master AND NOT type IN (pull_request)
      install: skip
      script: travis/release.sh um-login-persistence

notifications:
  slack: eoepca:Msk9hjQKAbwSYcVWiepenPim
  on_success: change
  on_failure: change
